# fill this out and then rename it to `config.yml` to use
secret:
  bot_token: ''
  db: ''
  dbhost: ''
  dbpass: ''
  dbuser: ''
  fortnite_key: ''
  gimage_keys:  # List of values
  gsearch_keys: # List of values
  imgur_id: ''
  rebrandly_key: ''
assets:
  emojis:
    alarm: ''
    badges:
      bug_hunter: ''
      bug_hunter_level_2: ''
      early_supporter: ''
      hypesquad: ''
      hypesquad_balance: ''
      hypesquad_bravery: ''
      hypesquad_brilliance: ''
      partner: ''
      staff: ''
      verified_bot_developer: ''
    channel_indicators:
      TextChannel: ''
      TextChannel-locked: ''
      TextChannel-nsfw: ''
      VoiceChannel: ''
      VoiceChannel-locked: ''
    check_button: ''
    default_avs: # List of values
    discordlogo: ''
    github:
      commit: ''
      license: ''
      location: ''
      star: ''
      watcher: ''
    infos:
      booster: ''
      bot: ''
      nitro: ''
      serverowner: ''
      system1: ''
      system2: ''
      veribot1: ''
      veribot2: ''
    loading: ''
    menus:
      menu_dleft: ''
      menu_dright: ''
      menu_left: ''
      menu_right: ''
      search: ''
    neutral_button: ''
    reddit:
      karma: ''
      trophies:
        Alpha Tester: ''
        Bellwether: ''
        Best Comment: ''
        Best Link: ''
        ComboCommenter: ''
        ComboLinker: ''
        Eight-Year Club: ''
        Eleven-Year Club: ''
        Extra Life 2019: ''
        Five-Year Club: ''
        Four-Year Club: ''
        Gilding I: ''
        Gilding II: ''
        Gilding III: ''
        Gilding IV: ''
        Gilding IX: ''
        Gilding V: ''
        Gilding VI: ''
        Gilding VII: ''
        Gilding VIII: ''
        Gilding X: ''
        Gilding XI: ''
        Inciteful Comment: ''
        Inciteful Link: ''
        New User: ''
        Nine-Year Club: ''
        Not Forgotten: ''
        One-Year Club: ''
        Open Sorcerer: ''
        RPAN Broadcaster: ''
        RPAN Viewer: ''
        Reddit Premium: ''
        Sequence | Editor: ''
        Sequence | Screenwriter: ''
        Seven-Year Club: ''
        Shutterbug: ''
        Six-Year Club: ''
        Ten-Year Club: ''
        Thirteen-Year Club: ''
        Three-Year Club: ''
        Twelve-Year Club: ''
        Two-Year Club: ''
        Undead | Lich: ''
        Undead | Necromancer: ''
        Undead | Zombie: ''
        Verified Email: ''
        Well-rounded: ''
        Xbox Live: ''
      upvote: ''
    status_emojis:
      dnd: ''
      idle: ''
      offline: ''
      online: ''
    toggleoff: ''
    toggleon: ''
    warning_button: ''
    x_button: ''
  exts: # List of values
  bot_guild_id: # Bot guild ID, this is an int
  guild_notifs_channel: # ID of channel where guild join/leave notifications will be sent

