bot_token: '' # discord bot token
db: '' # name of the database to connect to
dbhost: '' # host of the database
dbpass: '' # database password
dbuser: '' # user for database
fortnite_key: '' # api key for fortnite tracker api
gimage_keys: # list of keys to use for google image searches
  - ''
gsearch_keys: # list of keys to use for normal google searches
  - ''
github_token: '' # github api token
imgur_id: '' # imgur authorisation id
rebrandly_key: '' # rebrandly api key
