emoji_suite:
  'x_button': '<:x_:710365179929559060>'
  'check_button': '<:c_:710365173755543552>'
  'warning_button': '<:bwarn:710365241028116521>'
  'menu_right': '<:arrow_right:710365162082664459>'
  'menu_left': '<:arrow_back:710365153232814140>'
  'menu_dright': '<:track_forward:710365210338263060>'
  'menu_dleft': '<:track_backward:710365198963179520>'
  'neutral_button': '<:unicode_neutral:710365227354685520>'
  'alarm': '<:balarm_cl:710365167996764201>'
  'search': '<:search:710376307342704652>'
  'loading': '<a:loading:681628799376293912>'
license: |
  neo Discord bot
  Copyright (C) 2020 nickofolas

  neo is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published
  by the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  neo is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with neo.  If not, see <https://www.gnu.org/licenses/>.
number_emojis:
  '1': '1️⃣'
  '2': '2️⃣'
  '3': '3️⃣'
  '4': '4️⃣'
  '5': '5️⃣'
  '6': '6️⃣'
  '7': '7️⃣'
  '8': '8️⃣'
  '9': '9️⃣'
  '0': '0️⃣'
emoji_numbers:
  '1️⃣': '1'
  '2️⃣': '2'
  '3️⃣': '3'
  '4️⃣': '4'
  '5️⃣': '5'
  '6️⃣': '6'
  '7️⃣': '7'
  '8️⃣': '8'
  '9️⃣': '9'
  '0️⃣': '0'
emoji_dict:
  "online": '<:online:701474677775794176>'
  "dnd": '<:dnd2:700028690800705547>'
  "idle": '<:idle2:700028708844470402>'
  "offline": '<:offline3:700028748438700052>'
default_discord_users:
- '<:def0:704881247473893434>'
- '<:f1:704881276288761906>'
- '<:def2:704881316616732752>'
- '<:def3:704881302934913045>'
- '<:def4:705054900559806604>'
trophy_emojis:
  'Alpha Tester': '<:alpha_user:701169882317717575>'
  'Bellwether': '<:bellwether:701169890727559260>'
  'Best Comment': '<:bestcomment:701169898545741886>'
  'Best Link': '<:bestlink:701169905080467547>'
  'ComboCommenter': '<:combocommenter:701169912483152004>'
  'ComboLinker': '<:combolinker:701169919026528378>'
  'Eight-Year Club': '<:eightyearclub:701169925796134922>'
  'Eleven-Year Club': '<:elevenyearclub:701169931923750939>'
  'Five-Year Club': '<:fiveyearclub:701169947308589116>'
  'Four-Year Club': '<:fouryearclub:701169957978767361>'
  'Gilding I': '<:gilding:701169971052412969>'
  'Inciteful Comment': '<:incitefulcomment:701169979206140014>'
  'Inciteful Link': '<:incitefullink:701169989109022831>'
  'New User': '<:newuser:701170000194568243>'
  'Nine-Year Club': '<:nineyearclub:701170008499290173>'
  'Not Forgotten': '<:not_forgotten:701170020373495971>'
  'One-Year Club': '<:oneyearclub:701170033547804802>'
  'Reddit Premium': '<:reddit_gold:701170045816012842>'
  'RPAN Broadcaster': '<:rpanbroadcaster:701170060521111583>'
  'RPAN Viewer': '<:rpanviewer:701170069522088033>'
  'Sequence | Editor': '<:sequence_editor:701170078372200488>'
  'Sequence | Screenwriter': '<:sequence_text:701170086135726170>'
  'Seven-Year Club': '<:sevenyearclub:701170094000046160>'
  'Shutterbug': '<:shutterbug:701170101122105365>'
  'Six-Year Club': '<:sixyearclub:701170118587056228>'
  'Ten-Year Club': '<:tenyearclub:701170128103931905>'
  'Thirteen-Year Club': '<:thirteenyearclub:701170138589823176>'
  'Three-Year Club': '<:threeyearclub:701170146215198856>'
  'Twelve-Year Club': '<:twelveyearclub:701170156616810527>'
  'Two-Year Club': '<:twoyearclub:701170166440132609>'
  'Verified Email': '<:verifiedemailaddress:701170174849450034>'
  'Well-rounded': '<:wellrounded:701170182302859355>'
  'Xbox Live': '<:xboxlive:701223624866005002>'
  'Gilding X': '<:gildingx:701223644256534600>'
  'Gilding V': '<:gildingv:701223723306582036>'
  'Extra Life 2019': '<:extralife:701223603269664829>'
  'Gilding XI': '<:gildingxi:701223635763068989>'
  'Gilding IX': '<:gildingix:701223670227664996>'
  'Gilding VI': '<:gildingvi:701223708626255932>'
  'Gilding IV': '<:gildingiv:701223755199938590>'
  'Gilding II': '<:gildingii:701223770815463515>'
  'Undead | Lich': '<:undeadlich:701223584076660738>'
  'Gilding VII': '<:gildingvii:701223692021006368>'
  'Gilding III': '<:gildingiii:701223789249298462>'
  'Gilding VIII': '<:gildingviii:701223683561226250>'
  'Undead | Zombie': '<:undeadzombie:701223595845615626>'
  'Open Sorcerer': '<:opensorcerer:701223612132098108>'
  'Undead | Necromancer': '<:undeadnecromancer:701223562685710367>'
hl_langs:
- html.handlebars
- livecodeserver
- ruleslanguage
- vbscript-html
- actionscript
- clojure-repl
- coffeescript
- taggerscript
- applescript
- erlang-repl
- lassoscript
- mathematica
- mojolicious
- wildfly-cli
- apacheconf
- autohotkey
- dockerfile
- freepascal
- handlebars
- javascript
- livescript
- moonscript
- objectivec
- powershell
- processing
- typescript
- accesslog
- brainfuck
- capnproto
- instances
- jboss-cli
- nginxconf
- osascript
- purebasic
- smalltalk
- asciidoc
- cmake.in
- craftcms
- dsconfig
- html.hbs
- htmlbars
- makefile
- markdown
- openscad
- protobuf
- roboconf
- vbscript
- arduino
- aspectj
- clojure
- console
- crystal
- feature
- fortran
- gemspec
- gherkin
- haskell
- inform7
- lazarus
- mercury
- mipsasm
- oxygene
- parser3
- pf.conf
- podspec
- profile
- subunit
- verilog
- apache
- armasm
- autoit
- avrasm
- axapta
- ceylon
- coffee
- csharp
- delphi
- django
- docker
- elixir
- erlang
- fsharp
- golang
- gradle
- groovy
- hylang
- irpf90
- kotlin
- matlab
- maxima
- mkdown
- monkey
- nimrod
- pascal
- prolog
- puppet
- python
- scheme
- scilab
- step21
- stylus
- thrift
- x86asm
- xquery
- zephir
- basic
- capnp
- clean
- cmake
- crmsh
- excel
- gauss
- gcode
- graph
- https
- jinja
- julia
- lasso
- mizar
- nginx
- nixos
- obj-c
- ocaml
- patch
- plist
- scala
- shell
- smali
- stata
- swift
- vbnet
- xhtml
- xpath
- abnf
- adoc
- atom
- bash
- bind
- cson
- dart
- diff
- dust
- ebnf
- flix
- gams
- glsl
- golo
- haml
- haxe
- html
- http
- iced
- java
- json
- ldif
- leaf
- less
- lisp
- llvm
- mips
- moon
- n1ql
- nsis
- objc
- pcmk
- perl
- php3
- php4
- php5
- php6
- pony
- ruby
- rust
- scad
- scss
- stan
- step
- styl
- thor
- toml
- twig
- vala
- vhdl
- xlsx
- yaml
- zone
- ada
- ado
- arm
- awk
- bat
- bnf
- c++
- cal
- clj
- cls
- cmd
- coq
- cos
- cpp
- crm
- csp
- css
- dcl
- dfm
- dns
- dos
- dpr
- dst
- dts
- elm
- erb
- erl
- f90
- f95
- fix
- gms
- gss
- gyp
- h++
- hbs
- hpp
- hsp
- icl
- ini
- irb
- jsp
- jsx
- kdb
- lfm
- lpr
- lsl
- lua
- mak
- mel
- mkd
- mma
- moo
- nim
- nix
- p21
- pas
- pbi
- php
- qml
- rib
- rsl
- rss
- sci
- sml
- sqf
- sql
- stp
- svh
- tao
- tap
- tcl
- tex
- vbs
- vim
- xjb
- xls
- xml
- xsd
- xsl
- yml
- zep
- zsh
- as
- 1c
- bf
- cc
- cr
- cs
- do
- fs
- go
- hs
- hx
- hy
- i7
- js
- ls
- md
- mk
- ml
- mm
- nc
- pb
- pf
- pl
- pm
- pp
- ps
- py
- qt
- rb
- rs
- sh
- st
- sv
- tk
- tp
- ts
- vb
- xl
- xq
- c
- d
- h
- k
- m
- q
- r
- v
